DROP TABLE IF EXISTS matrices;

CREATE TABLE matrices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    value1 INTEGER NOT NULL,
    value2 INTEGER NOT NULL,
    value3 INTEGER NOT NULL,
    value4 INTEGER NOT NULL,
    value5 INTEGER NOT NULL,
    value6 INTEGER NOT NULL,
    value7 INTEGER NOT NULL,
    value8 INTEGER NOT NULL,
    value9 INTEGER NOT NULL
);

